service: my-gcf-service # NOTE: Don't put the word "google" in here

provider:
  name: google
  runtime: nodejs4.3
  project: my-project-1234
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package and it's dependencies should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - package.json
    - .git/**

functions:
  first:
    handler: http
    events:
      - http: path
  
  # NOTE: the following uses an "event" event (an pubSub event in this case).
  # Please create the corresponding resources before deploying through Serverless
  
  #second:
  #  handler: event
  #  events:
  #    - event:
  #        eventType: providers/cloud.pubsub/eventTypes/topic.publish
  #        resource: projects/*/topics/my-topic
